import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

export interface PDFExportOptions {
  title: string
  content: string
  filename?: string
  includeLogo?: boolean
  includeTimestamp?: boolean
}

/**
 * Generate Eva-Tech Studio branded PDF from HTML content
 * Includes logo in header, branding colors, and professional formatting
 */
export async function generatePDF(options: PDFExportOptions): Promise<jsPDF> {
  const {
    title,
    content,
    filename = 'eva-tech-export.pdf',
    includeLogo = true,
    includeTimestamp = true
  } = options

  // Create PDF document
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  })

  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const margin = 15
  let currentY = margin

  // Define brand colors
  const brandColors = {
    dark: '#07080F',
    gold: '#C9A96E',
    lightText: '#E8E3D8',
    dimText: '#6B6860'
  }

  // Set up page styling
  pdf.setFont('helvetica')

  // Add Eva-Tech Studio branding header
  if (includeLogo) {
    // Header background (dark obsidian color)
    pdf.setFillColor(7, 8, 15) // #07080F
    pdf.rect(0, 0, pageWidth, 30, 'F')

    // Gold accent line under header
    pdf.setDrawColor(201, 169, 110) // #C9A96E
    pdf.setLineWidth(1)
    pdf.line(margin, 28, pageWidth - margin, 28)

    // Logo/Branding text
    pdf.setTextColor(201, 169, 110) // Gold
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(14)
    pdf.text('EVA-TECH STUDIO', margin, 12)

    // Subtext
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(8)
    pdf.setTextColor(107, 104, 96) // Dim text color
    pdf.text('Growth-Driven Digital Agency | AI-Generated Report', margin, 18)

    // Timestamp
    if (includeTimestamp) {
      pdf.setFontSize(7)
      const now = new Date().toLocaleString('en-ZA', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      })
      pdf.text(`Generated: ${now}`, pageWidth - margin - 40, 18)
    }

    currentY = 35
  }

  // Add title section
  pdf.setTextColor(232, 227, 216) // Light text
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(16)

  const titleLines = pdf.splitTextToSize(title, pageWidth - 2 * margin)
  pdf.text(titleLines, margin, currentY)
  currentY += titleLines.length * 8 + 10

  // Add content
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(11)
  pdf.setTextColor(107, 104, 96) // Dark gray text for readability

  // Split content into lines that fit the page width
  const contentLines = pdf.splitTextToSize(content, pageWidth - 2 * margin)

  for (const line of contentLines) {
    if (currentY + 5 > pageHeight - margin) {
      // Add new page if content exceeds current page
      pdf.addPage()
      currentY = margin

      // Re-add header on new page
      if (includeLogo) {
        pdf.setFillColor(7, 8, 15)
        pdf.rect(0, 0, pageWidth, 20, 'F')
        pdf.setDrawColor(201, 169, 110)
        pdf.line(margin, 18, pageWidth - margin, 18)

        pdf.setTextColor(201, 169, 110)
        pdf.setFont('helvetica', 'bold')
        pdf.setFontSize(10)
        pdf.text('EVA-TECH STUDIO', margin, 10)

        currentY = 25
      }

      pdf.setTextColor(107, 104, 96)
      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(11)
    }

    pdf.text(line, margin, currentY)
    currentY += 5
  }

  // Add footer
  const pageCount = (pdf as any).getNumberOfPages?.() || 1
  pdf.setFontSize(8)
  pdf.setTextColor(147, 140, 130) // Lighter gray
  pdf.text(
    `Page 1 of ${pageCount}`,
    pageWidth / 2,
    pageHeight - 8,
    { align: 'center' }
  )

  // Add bottom branding
  pdf.setDrawColor(201, 169, 110)
  pdf.setLineWidth(0.5)
  pdf.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12)

  pdf.setFontSize(7)
  pdf.setTextColor(107, 104, 96)
  pdf.text(
    'This document was generated by Eva-Tech Studio AI. © 2026 Eva-Tech Studio. All rights reserved.',
    margin,
    pageHeight - 5
  )

  return pdf
}

/**
 * Download generated PDF to user's device
 */
export async function downloadPDF(
  pdf: jsPDF,
  filename: string = 'eva-tech-export.pdf'
): Promise<void> {
  // Ensure filename ends with .pdf
  const finalFilename = filename.endsWith('.pdf') ? filename : `${filename}.pdf`
  pdf.save(finalFilename)
}

/**
 * Generate PDF from HTML element (for client-side rendering)
 */
export async function generatePDFFromHTML(
  element: HTMLElement,
  title: string,
  filename?: string
): Promise<jsPDF> {
  try {
    // Convert HTML element to canvas
    const canvas = await html2canvas(element, {
      scale: 2,
      logging: false,
      backgroundColor: '#07080F'
    })

    // Create PDF from canvas
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    })

    const pageWidth = pdf.internal.pageSize.getWidth()
    const pageHeight = pdf.internal.pageSize.getHeight()
    const imgWidth = pageWidth - 30
    const imgHeight = (canvas.height * imgWidth) / canvas.width

    // Add header
    pdf.setFillColor(7, 8, 15)
    pdf.rect(0, 0, pageWidth, 25, 'F')

    pdf.setTextColor(201, 169, 110)
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(14)
    pdf.text('EVA-TECH STUDIO', 15, 12)

    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(8)
    pdf.setTextColor(107, 104, 96)
    pdf.text(title, 15, 18)

    // Add canvas content
    const imgData = canvas.toDataURL('image/png')
    pdf.addImage(imgData, 'PNG', 15, 30, imgWidth, imgHeight)

    return pdf
  } catch (error) {
    console.error('[PDF] Error generating PDF from HTML:', error)
    throw new Error('Failed to generate PDF from HTML element')
  }
}

/**
 * Format text content for PDF export (removes HTML tags, cleans formatting)
 */
export function formatTextForPDF(text: string): string {
  // Remove HTML tags
  let cleaned = text.replace(/<[^>]*>/g, '')

  // Decode HTML entities
  const textarea = document.createElement('textarea')
  textarea.innerHTML = cleaned
  cleaned = textarea.value

  // Normalize whitespace
  cleaned = cleaned.replace(/\n\s*\n/g, '\n\n').trim()

  return cleaned
}
